INSERT INTO TBL_CATEGORY (NAME) VALUES ('Fabricação Própria');
INSERT INTO TBL_CATEGORY (NAME) VALUES ('Nacional');
INSERT INTO TBL_CATEGORY (NAME) VALUES ('Importado');
INSERT INTO TBL_CATEGORY (NAME) VALUES ('Premium');

-- INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, CATEGORY_ID, PROMOTION, NEW_PRODUCT, PRICE) VALUES ('Produto 01', 'Description 01', 1, true, true, 100);
-- INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, CATEGORY_ID, PROMOTION, NEW_PRODUCT, PRICE) VALUES ('Produto 02', 'Description 02', 2, false, true, 200);
-- INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, CATEGORY_ID, PROMOTION, NEW_PRODUCT, PRICE) VALUES ('Produto 03', 'Description 03', 3, true, false, 300);
-- INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, CATEGORY_ID, PROMOTION, NEW_PRODUCT, PRICE) VALUES ('Produto 04', 'Description 04', 4, false, false, 400);

INSERT
INTO TBL_PRODUCT(NAME,DESCRIPTION,PRICE,CATEGORY_ID,PROMOTION, NEW_PRODUCT)
VALUES('Computador XP','I9,SSD500,HD1T, 32GB', 5999.99,1,true,true);          

INSERT
INTO TBL_PRODUCT(NAME,DESCRIPTION,PRICE,CATEGORY_ID,PROMOTION, NEW_PRODUCT)
VALUES('Computador XR','I7,SSD500,HD1T, 16GB', 4999.99,2,true,false);  

INSERT
INTO TBL_PRODUCT(NAME,DESCRIPTION,PRICE,CATEGORY_ID,PROMOTION, NEW_PRODUCT)
VALUES('Computador XR','I7,SSD256,HD1T, 16GB', 4599.99,3,false,false);  

INSERT
INTO TBL_PRODUCT(NAME,DESCRIPTION,PRICE,CATEGORY_ID,PROMOTION, NEW_PRODUCT)
VALUES('Computador XR','I7, HD1T, 16GB', 4000,4,false,false);  